### ISSUE TITLE
Complete Spotify integration

### ISSUE THREAD

**Issue by HenegarCodes** [bkness/jungle-map-api#8]
To make it work, need to complete the OAuth2 flow by:

Redirecting the user to the Spotify authorization URL.
Handling the callback from Spotify to extract the authorization code.
Sending a POST request to Spotify's token endpoint to exchange the authorization code for an access token.
Handling the response from the token endpoint, including storing the access token and handling token expiration.
Making authenticated requests to the Spotify API using the obtained access token.

**Comment by bkness** [comment]
My homework is taking wayh longer than anticipated but I will get around to it soon. Almost finished with my weather app
